### ISSUE TITLE
Move Atomic CSS to a new Github organization?

### ISSUE THREAD

**Issue by pankajparashar** [acss-io/acss-site#106]
> I reckon this is going to be shelved even before it is put into consideration. But I'll still take a jab at this anyways :-) **Warning:- It is long!**

**Context**
I feel that the interest and the adoption of Atomic CSS in the community is growing by the day. Developers (both in and outside of Yahoo) have been doing an incredible job to build additional toolset, to make adoption of Atomic CSS architecture easier from small to large scale projects. This has led to the development of a number of useful repositories that are scattered across the face of Github.

**Problem Statement**
I'm afraid that this growing interest in the masses will die soon, unless we do something about it. A no. of projects like [tachyons-css](https://github.com/tachyons-css), [blank-css](https://github.com/blank-css) and many more are based on the same Atomic CSS principle, a few of them are already very popular among the developer community. (eg., **tachyons**). These projects although quite small, already operate under a separate organization. The growing competition warrants a change in the overall direction.

**What are the benefits of moving to a new organization?**
- Consolidation of all the build tools, editor plugins, integrations with other frameworks, branding etc under a single umbrella.
- Makes finding things (all related to Atomic CSS) easier.
- Offers clear direction to fellow developers who also want to contribute to Atomic CSS.
- As the project grows big, it becomes easier to split and manage multiple repositories, while still being under the same umbrella. See what [Bootstrap](https://github.com/twbs) has done after moving outside of Twitter.
- A possible re-incarnation of the project, after key folks leaving the organization. This will ensure that the project continues to grow despite people going away.

**Known limitations**
I do understand that, with Yahoo being in the picture, this idea will be difficult to sail through. But if somehow it does, we can organize the repositories in the following way,

```
acss-io (organization)
    .
    ├── acss-site
        : Main website for Atomic CSS
    ├── atomizer
        : NPM module to generate Atomic CSS
    ├── atomizer-web
        : Online tool for Atomizer
    ├── acss-rules
        : JSON rules to be maintained separately (will be used by Atomizer and other tools)
    ├── atomize-io
        : Online tool that shows the net benefit of using Atomic CSS
    ├── editor-plugins
        : Extensions, packages, plugins and snippets for popular editors 
    ├── yo-generators
        : Yeoman generators for bootstrapping a basic site and integrations with other frameworks like react, polymer, fluxible etc.
    ├── build-plugins
        : Grunt, Gulp, Webpack plugins to use Atomizer
    ├── acss-showcase
        : Gallery of websites using Atomic CSS
    ├── community-articles
        : Articles written by community related to Atomic CSS
    └── branding-logos
        : As the name suggests :-)
```

> The name of the repositories is subject to discussion. But it offers a great way of consolidating everything related to Atomic CSS under the same umbrella.

Most of the repositories already exists, somewhere across Github. Its just a matter of consolidating all of them under the same organization. Thoughts? /cc @thierryk @src-code @redonkulus

**Comment by thierryk** [comment]
I like this idea a lot and I don't think Yahoo would have much to say in this case since this would mostly be a consolidation of various resources (@src-code or @redonkulus could stil ask Gil ay Yahoo though).

@pankajparashar, this being your idea and seeing all you've done already, I think you could actually own this if you wanted. 

I'm curious to know what @renatoi, @src-code, and @redonkulus think about this.

**Comment by renatoi** [comment]
I'm in favor of having acss as its own organization. As Thierry mentioned, @src-code and @redonkulus would have to look with Gil to see if it's possible. Another thing that might be worth checking is its current license. The current one (I believe it's BSD) is still very good but I don't know if there's any restrictions or problems with the copyright.

Anyway, I agree with this approach and I believe it would be beneficial.

**Comment by src-code** [comment]
Worth considering, as there isn't much ongoing support from Yahoo right now (me being the last remaining team member since @thierryk and @renatoi left, and I'm not working on Atomic anymore.)  Though it is still used on projects at Yahoo.  Might make sense to move this out and change ownership, if @pankajparashar or another wants to take that on.  But I'll have to check with people here to see what the process would be.  It'd also require moving the docs site to another host, BTW.

It'll take me a little time to pick this up as I'm crunched with other work, but hopefully soon I can get more information for all of you.
